// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_g-fve6VnFdr3qECBeiMGEfMJ4obi10',
    appId: '1:971087564701:web:56b1be96c184c958e32974',
    messagingSenderId: '971087564701',
    projectId: 'test-hosting-feb11',
    authDomain: 'test-hosting-feb11.firebaseapp.com',
    storageBucket: 'test-hosting-feb11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt_8jPtIQXqOQW6GmOKdpHaG1MoEyRZd8',
    appId: '1:971087564701:android:24a1e7c330c04c19e32974',
    messagingSenderId: '971087564701',
    projectId: 'test-hosting-feb11',
    storageBucket: 'test-hosting-feb11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtCQju7N6C6EehU0xrdi7zhDZeH_Ycfc',
    appId: '1:971087564701:ios:9885fffdf77da876e32974',
    messagingSenderId: '971087564701',
    projectId: 'test-hosting-feb11',
    storageBucket: 'test-hosting-feb11.firebasestorage.app',
    iosBundleId: 'com.example.restCurdFoto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtCQju7N6C6EehU0xrdi7zhDZeH_Ycfc',
    appId: '1:971087564701:ios:9885fffdf77da876e32974',
    messagingSenderId: '971087564701',
    projectId: 'test-hosting-feb11',
    storageBucket: 'test-hosting-feb11.firebasestorage.app',
    iosBundleId: 'com.example.restCurdFoto1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ_g-fve6VnFdr3qECBeiMGEfMJ4obi10',
    appId: '1:971087564701:web:1d604c480391d0d1e32974',
    messagingSenderId: '971087564701',
    projectId: 'test-hosting-feb11',
    authDomain: 'test-hosting-feb11.firebaseapp.com',
    storageBucket: 'test-hosting-feb11.firebasestorage.app',
  );
}
